feat: converted discrete cleanup to typescript
MapColonies/discrete-cleanup pull request #1
Opened 2021-11-17 12:44 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✔                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-11-18 07:58 UTC, yossiz16 approved these changes

2021-11-21 08:00 UTC, asafMasa requested changes

2021-11-21 08:00 UTC, asafMasa commented on src/clients/jobManagerClient.ts
> +      type: this.ingestionJobType,
check if "shouldReturnTasks" can be usefull here

2021-11-21 08:00 UTC, asafMasa commented on src/clients/jobManagerClient.ts
> +      isCleaned: false,
check if "shouldReturnTasks" can be usefull here

2021-11-21 08:00 UTC, asafMasa commented on tests/unit/storageProviders/fs/fsSourcesStorageProvider.spec.ts
> +  it('Checks tiffs parser functionality', async () => {
Checks tiffs parser?

2021-11-21 09:51 UTC, asafMasa approved these changes

2021-11-21 09:51 UTC, merged