refactor: change to class, add unit tests
MapColonies/discrete-cleanup pull request #13
Opened 2021-03-16 15:10 UTC by AnguIar

2021-03-16 16:30 UTC, asafMasa requested changes
Good job!!
liked the refactor 💣

2021-03-16 16:30 UTC, asafMasa commented on src/cleanup_script.js
> +  async deleteChunks(urisArray) {
rename to deleteFsChunks

2021-03-16 16:30 UTC, asafMasa commented on src/cleanup_script.js
> +  async parseItemsFromS3(Prefix, ContinuationToken) {
it seams as actual delete not parse, am i wrong? rename is needed?

2021-03-16 16:30 UTC, asafMasa commented on src/cleanup_script.js
> +    const mapproxyUrl = config.get('mapproxy_api').url;
add info log of the layer that is about to be deleted

2021-03-16 16:30 UTC, asafMasa commented on src/cleanup_script.js
> +    const mapproxyUrl = config.get('mapproxy_api').url;
do we need to check if the layer exists before trrying to delete it?

2021-03-17 07:34 UTC, AnguIar commented on src/index.js
> +new CleanupScript()
This doesn't work. If you want to use `try-catch` you'll need `await` - but you _cant_ `await` in global scope.

2021-03-17 07:36 UTC, AnguIar commented on src/cleanup_script.js
> +  async parseItemsFromS3(Prefix, ContinuationToken) {
It is one step before delete. Deletion from `s3` takes place in `deleteFromS3`

2021-03-17 07:37 UTC, AnguIar commented on src/cleanup_script.js
> +    const mapproxyUrl = config.get('mapproxy_api').url;
There is a log

2021-03-17 11:30 UTC, asafMasa requested changes

2021-03-17 11:30 UTC, asafMasa commented on src/cleanup_script.js
> +      this.logger.info(
seperate Not_Found to other exceptions

2021-03-17 13:52 UTC, asafMasa approved these changes

2021-03-17 13:52 UTC, merged