chore: added displayPath support
MapColonies/discrete-cleanup pull request #20
Opened 2022-09-18 11:41 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-09-18 11:47 UTC, cl-shaharshavit-rnd requested changes

2022-09-18 11:47 UTC, cl-shaharshavit-rnd commented on src/storageProviders/s3/s3TileStorageProvider.ts
> +    console.log(itemsToDelete)
remove console

2022-09-18 12:57 UTC, asafMasa requested changes
update mc-models package if it's been used

2022-09-18 12:57 UTC, asafMasa commented on src/storageProviders/fs/fsTileStorageProvider.ts
> +      return path.join(this.fsTilesLocation, discrete.parameters.layerRelativePath);
fix lint

2022-09-19 13:58 UTC, CL-SHLOMIKONCHA commented on src/storageProviders/fs/fsTileStorageProvider.ts
> +      return path.join(this.fsTilesLocation, discrete.parameters.layerRelativePath);
fixed

2022-09-21 15:08 UTC, asafMasa approved these changes

2022-09-22 07:12 UTC, cl-shaharshavit-rnd approved these changes

2022-09-22 07:18 UTC, merged