Incoming sync cleanup
MapColonies/discrete-cleanup pull request #3
Opened 2021-11-29 08:16 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-11-29 11:27 UTC, asafMasa requested changes

2021-11-29 11:27 UTC, asafMasa commented on helm/templates/configmap.yaml
> +  FAILED_SYNC_CLEANUP_DELAY_DAYS: {{ .Values.env.failedCleanupDelayDays.sync | quote }}
Add incoming_sync_job_type

2021-11-29 11:27 UTC, asafMasa commented on helm/values.yaml
> +    sync: 14
add incoming_sync_job_type value

2021-11-29 11:30 UTC, asafMasa approved these changes

2021-12-01 08:06 UTC, yossiz16 approved these changes

2021-12-01 08:14 UTC, merged