fix: origin directory prefix + added expired batch condition
MapColonies/discrete-cleanup pull request #38
Opened 2024-03-18 12:44 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2024-03-21 11:35 UTC, asafMasa requested changes

2024-03-21 11:35 UTC, asafMasa commented on src/cleanupCommand/cleanupManager.ts
> +      if (expiredBatch.length > 0) {
if (expiredBatch.length == 0) { continue; }

2024-03-21 11:35 UTC, asafMasa commented on src/cleanupCommand/cleanupManager.ts
> +        this.sourceBlackList.includes(extractRootDirectory(discrete.parameters.originDirectory))
please create a method and reuse it 
```
isIncludedInBlaclist(directory: string) {
   return this.sourceBlackList.includes(extractRootDirectory(directory));
} 
```

2024-03-25 11:19 UTC, CL-SHLOMIKONCHA commented on src/cleanupCommand/cleanupManager.ts
> +      if (expiredBatch.length > 0) {
fixed

2024-03-25 11:19 UTC, CL-SHLOMIKONCHA commented on src/cleanupCommand/cleanupManager.ts
> +        this.sourceBlackList.includes(extractRootDirectory(discrete.parameters.originDirectory))
fixed

2024-03-31 07:34 UTC, asafMasa approved these changes

2024-04-07 06:58 UTC, merged